### ISSUE TITLE
Add an introduction to the 'Building Content' chapter

### ISSUE THREAD

**Issue by adahms** [redhat-documentation/community-collaboration-guide#32]
A brief introduction must be added to the start of the Supported Tools chapter to outline the purpose of the chapter and the content that it covers.

The introduction must cover the following -

* What should readers know before they begin reading?
* What does the chapter cover?
* What will readers come away with after reading?

**Comment by pmkovar** [comment]
@nengard I'd suggest renaming "Supported Tools" to "Building Content", because that's what the chapter really describes.

While we are at it, let's also consider moving "Rendering Content" to "Building Content" (and rename it to "Rendering Content Locally" or something like that). Maybe that's something to address with #43?

**Comment by nengard** [comment]
Yes @pmkovar we talked about moving this content in our last meeting.  I agree with you 100%.

**Comment by finp** [comment]
@pmkovar  you beat me to it! can we close this issue (32)? or is there still work to do?

**Comment by finp** [comment]
@adahms  To be consistent with other chapters, I kept it short, and didn't link to sections, is that the style required? 
https://github.com/redhat-documentation/community-collaboration-guide/pull/71

**Comment by nengard** [comment]
I forgot to close this.  We have merged this addition! Thanks @finp
