### ISSUE TITLE
Add section explaining AsciiDoc attribute files

### ISSUE THREAD

**Issue by inoxx03** [redhat-documentation/community-collaboration-guide#76]
The content for this section should briefly explain:

* what an `attributes.adoc` file is and why is it useful when creating books
* what necessary elements that an attributes file must contain (for instance, `doctype` must be specified)
* A breakdown of the structure of a simple `attributes.adoc`. (an embedded `adoc` source with callouts on important lines would be the fomatting I'd prefer, but I'm open to suggestions here:))
* Examples of more advanced attribute file usage, such as defining replaceable variables for book, chapter,component or package names, URLs, etc ,...
* Also, it might be useful for the section to demonstrate how replaceable variables can be further used to pre-defined create link URLs

Please feel free to add content suggestions for useful information that the chapter should include, if anything comes to your mind:)

**Comment by inoxx03** [comment]
@nengard Right, my bad, I completely skimmed over that one and missed it when checking the guide.I'll go over our existing content to see where it can be improved:)

**Comment by nengard** [comment]
No worries! I did too! I'm the one who said we didn't have it in the guide yet :)

**Comment by jenmalloy** [comment]
+1 to @inoxx03 suggestions, in particular how to "build out" link URLs with replaceables/variables. It's a great way to avoid hardcoding and really powerful for that reason.

Also, how to handle the product attributes file would be useful, since that's where things can get tricky if you are mirroring the upstream repo downstream. Since I'm working through this right now, I can write up my findings after I get it all figured out.

**Comment by inoxx03** [comment]
I've made some additions to the AsciiDoc chapter. The changes are introduced by [PR #94](https://github.com/redhat-documentation/community-collaboration-guide/pull/94).
